### ISSUE TITLE
Column mapping doesn't support omitted columns (such as auto-increment)

### ISSUE THREAD

**Issue by elibwhitems** [microsoft/sql-spark-connector#14]
In matchSchemas, it seems auto-increment columns are not accounted for. This is causing my write (using SaveMode.Overwrite and truncate = true) to fail.

https://github.com/microsoft/sql-spark-connector/blob/b4eaff72794034a1abf263e78c4e45a4a3e97899/src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/BulkCopyUtils.scala#L244-L245

**Comment by elibwhitems** [comment]
Sorry, seems this issue is not just with this check, but also with the column mapping logic

**Comment by shivsood** [comment]
@elibwhitems Hope i understood your issue -   You are trying to save a dataframe with without a given column as that's an auto-incremented column. Right? That's not supported for now. Can u please send your sample here for refrence and repro the problem.

**Comment by elibwhitems** [comment]
@shivsood, yes, that's right. The dataframe doesn't have that column because it is an auto-increment column in the SQL DB. I can try to create a minimal repro script in the next day or two

**Comment by SrinadhaYarram-SEGH** [comment]
jdbc connector supporting data loads into tables with PK with Identity on.
But Spark Connector fails with columns count mismatch.

**Comment by prasanna-sk** [comment]
Facing the same issue with "Identity" column defined with a seen and increment. 

https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15

Below is the error. 
```
An error occurred while calling o237.save.
: java.sql.SQLException: Spark Dataframe and SQL Server table have differing numbers of columns
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.com$microsoft$sqlserver$jdbc$spark$BulkCopyUtils$$assertCondition(BulkCopyUtils.scala:526)
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.matchSchemas(BulkCopyUtils.scala:244)
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.getColMetaData(BulkCopyUtils.scala:207)
	at com.microsoft.sqlserver.jdbc.spark.Connector.write(Connector.scala:66)
	at com.microsoft.sqlserver.jdbc.spark.DefaultSource.createRelation(DefaultSource.scala:51)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:276)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rajmera3** [comment]
Solved in #52

**Comment by sdebruyn** [comment]
@rajmera3 the fix didn't work

**Comment by arvindshmicrosoft** [comment]
@sdebruyn - can you look at #81 and specifically the repro therein, to clarify your comment about this earlier fix not working? I want to check if it is the same thing I ran into (and have fixed in the PR).

**Comment by savageawakening** [comment]
Sorry to comment on this old issue but it's unclear whether there is a setting that is required to resolve this issue or if it is just supposed to work? I am on 1.0.2 with spark 2.4. I see from the releases that this fix was put in to 1.0.1 but I am still experiencing this problem. I am writing to an Azure SQL db with the example code provided in the readme for append.

**Comment by kaykumar** [comment]
This seems not working still with connector version com.microsoft.azure:spark-mssql-connector_2.12:1.2.0.

the workaround for now is to add id column with a 0 as value and MSSQL will auto increment it.
